[2024-10-17T18:43:36.719+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-17T18:43:36.731+0000] {taskinstance.py:2602} INFO - Dependencies not met for <TaskInstance: direct_load_etl.extract manual__2024-10-17T18:43:36.763485+00:00 [queued]>, dependency 'Execution Date' FAILED: Execution date 2024-10-17T18:43:36.763485+00:00 is in the future (the current date is 2024-10-17T18:43:36.731377+00:00).
[2024-10-17T18:43:36.733+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
